version: '2'

volumes:
  jenkins_home:
    external: true

services:
  jenkins:
    build:
      context: .
      args:
        DOCKER_GID: ${DOCKER_GID}
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080"

  jenkins-slave:
    build:
      context: .
      dockerfile: Dockerfile.slave
      args:
        DOCKER_GID: ${DOCKER_GID}
        JENKINS_SLAVE_VERSION: ${JENKINS_SLAVE_VERSION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - java
      - -jar
      - slave.jar
      - -master
      - http://jenkins:8080/
      - -username
      - ${JENKINS_USERNAME}
      - -password
      - ${JENKINS_PASSWORD}
      - -executors
      - "1"
      - -labels
      - ${JENKINS_SLAVE_LABELS}