version: '2.1'

volumes:
  jenkins_home:
    external: true

services:
  jenkins:
    build:
      context: .
      args:
        DOCKER_GID: ${DOCKER_GID}
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      JENKINS_USERNAME: ${JENKINS_USERNAME}
      KMS_JENKINS_PASSWORD: ${KMS_JENKINS_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:8080/login"]
      interval: 5s
      retries: 60
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080"
  jenkins-slave:
    build:
      context: .
      dockerfile: Dockerfile.slave
      args:
        DOCKER_GID: ${DOCKER_GID}
        JENKINS_SLAVE_VERSION: ${JENKINS_SLAVE_VERSION}
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      JENKINS_USERNAME: ${JENKINS_USERNAME}
      JENKINS_SLAVE_LABELS: ${JENKINS_SLAVE_LABELS}
      KMS_JENKINS_PASSWORD: ${KMS_JENKINS_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock